services:
    CleverAge\ProcessSoapBundle\Task\:
        resource: '../../Task/*'
        autowire: true
        public: true
        shared: false
        tags:
            - { name: monolog.logger, channel: cleverage_process_task }

    CleverAge\ProcessSoapBundle\Task\SoapClientTask:
        autowire: true
        public: true
        shared: false
        calls:
            - method: 'setContainer'
              arguments:
                - '@service_container'
        tags:
            - { name: monolog.logger, channel: cleverage_process_task }

